project_id = "rhkfocbexlfvijomzppx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = ["http://localhost:8080/auth", "http://localhost:5173/auth"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.google]
enabled = false
# Раскомментируйте и добавьте ваши credentials после создания OAuth приложения в Google Cloud Console
# client_id = "your-client-id.apps.googleusercontent.com"
# secret = "your-client-secret"

[analytics]
enabled = false